### ISSUE TITLE
Unexpected TS issue with the type of css function

### ISSUE THREAD

**Issue by Barbapapazes** [Tahul/pinceau#76]
Hello,

Here an error with the css function. Does anyone know how to deals with it ?

![image](https://user-images.githubusercontent.com/45267552/226418634-669d72e2-6aaf-4458-91dd-0edbb3ba006e.png)

**Comment by Barbapapazes** [comment]
I was using TS beta so 5.1.0-dev.xxxxx. With TS 4.9.5, it seems to be ok.

**Comment by Barbapapazes** [comment]
Solution was here https://pinceau.dev/get-started/installation#volar

**Comment by agenordebriat** [comment]
@Barbapapazes  @Tahul Any idea on why I'm getting the same issue? Pinceau works fine except for this.

Setup :
- Volar 1.8.4 in Take Over Mode. Tried a few different versions just in case.
- Pinceau 0.19.2 w/ VS Code extension @0.4.1
- Nuxt 3.6.2

Did a simple `npx nuxi init <project>` and only added `pinceau/nuxt` as a module.
Providing a `tokens.config.ts` – copy/pasted from the documentation – didn't change anything.

**Comment by Barbapapazes** [comment]
Haye you tried to add some config to your ts config?

https://pinceau.dev/get-started/installation/#volar

**Comment by agenordebriat** [comment]
My `tsconfig.json` file already had everything it needed, since I'm on Nuxt using the module, except the last `"pinceau.css"` path.

I added `"pinceau.css": ["/<path to my project>/.nuxt/pinceau/theme.css"], and it got rid of the error. Thing is, it should be there from the get go!
I'll have a look at it and open a PR to fix this.
I'll open a different issue now because CSS properties are not being auto-completed. 

The content of the `.nuxt/pinceau/utils.ts` file look wrong:
```ts
import { PinceauTheme, PropertyValue } from 'pinceau'

export const utils = undefined

export type GeneratedPinceauUtils = typeof utils

export default utils
```

Thanks for having me look at the doc again.
